# Generated by Django 3.1 on 2020-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
                ('img', models.ImageField(upload_to='pics')),
                ('about', models.TextField()),
            ],
        ),
    ]
